#Лабораторная работа №1
Создание нейронной сети, выполняющей бинарную классификацию

##Теоретическая часть

In [ ]:
import numpy as np
import random

Создадим цифры, из которых будет состоять наш датасет

In [ ]:
numbers = list()
numbers.append(([[1, 1, 1],
                 [1, 0, 1],
                 [1, 0, 1],
                 [1, 0, 1],
                 [1, 1, 1]], 0))

In [ ]:
numbers.append(([[0, 0, 1],
                 [0, 0, 1],
                 [0, 0, 1],
                 [0, 0, 1],
                 [0, 0, 1]], 1))

numbers.append(([[1, 1, 1],
                 [0, 0, 1],
                 [1, 1, 1],
                 [1, 0, 0],
                 [1, 1, 1]], 2))

numbers.append(([[1, 1, 1],
                 [0, 0, 1],
                 [1, 1, 1],
                 [0, 0, 1],
                 [1, 1, 1]], 3))

numbers.append(([[1, 0, 1],
                 [1, 0, 1],
                 [1, 1, 1],
                 [0, 0, 1],
                 [0, 0, 1]], 4))

numbers.append(([[1, 1, 1],
                 [1, 0, 0],
                 [1, 1, 1],
                 [0, 0, 1],
                 [1, 1, 1]], 5))

numbers.append(([[1, 1, 1],
                 [1, 0, 0],
                 [1, 1, 1],
                 [1, 0, 1],
                 [1, 1, 1]], 6))

numbers.append(([[1, 1, 1],
                 [0, 0, 1],
                 [0, 0, 1],
                 [0, 0, 1],
                 [0, 0, 1]], 7))

numbers.append(([[1, 1, 1],
                 [1, 0, 1],
                 [1, 1, 1],
                 [1, 0, 1],
                 [1, 1, 1]], 8))

numbers.append(([[1, 1, 1],
                 [1, 0, 1],
                 [1, 1, 1],
                 [0, 0, 1],
                 [1, 1, 1]], 9))

Сформируем датасет

In [ ]:
dataset = list()
for i in range(10000):
  dataset.append(random.choice(numbers))

Выведем случайную цифру из датасета

In [ ]:
random.choice(dataset)

([[1, 1, 1], [1, 0, 1], [1, 1, 1], [1, 0, 1], [1, 1, 1]], 8)

Заполним единицами вектор весов связей между нейронами

In [ ]:
first_layer_weights = np.ones((15, 1))

Создадим функцию активации, возвращающую единицу, если сумма полученных сигналов выше определенного порога

In [ ]:
def result_bin_class(result):
  if (result > 8):
    return True
  else:
    return False

Создадим функцию подсчета суммарного веса полученных сигналов

In [ ]:
def calculate_res(input_number, first_layer_weights):
  sum = 0
  for i in range(15):
    sum += input_number[0][i//3][i%3] * first_layer_weights[i]
  return sum

Зададим функцию, формирующую сигнал корректировки весов в зависимости от соотношения ответа нейронной сети и правильного ответа

In [ ]:
def weight_changing(positive, target):
  k = 0
  if (positive and not target):
    k = -0.1
  elif (not positive and target):
    k = 0.1
  return k

Пропишем функции для обучения нейронной сети

In [ ]:
def learn(input_number, first_layer_weights, target):
  k = weight_changing(result_bin_class(calculate_res(input_number, first_layer_weights)), True if input_number[1] == target else False)
  for i in range(15):
    first_layer_weights[i] += input_number[0][i//3][i%3] * k
  return first_layer_weights

In [ ]:
def train_nn(input_dataset, first_layer_weights, target, size_of_data):
  for i in range(size_of_data):
    first_layer_weights = learn(random.choice(input_dataset), first_layer_weights, target)

In [ ]:
train_nn(dataset, first_layer_weights, 1, 800)

In [ ]:
first_layer_weights

array([[-0.2],
       [-0.1],
       [ 1.6],
       [-0.1],
       [ 1. ],
       [ 1.7],
       [-0.2],
       [ 0.1],
       [ 1.6],
       [ 0.1],
       [ 1. ],
       [ 1.7],
       [-0.1],
       [-0.1],
       [ 1.6]])

Создадим функции для тестирования обученной нейронной сети

In [ ]:
def test(input_number, first_layer_weights, target):
  if (result_bin_class(calculate_res(input_number, first_layer_weights)) == (True if input_number[1] == target else False)):
    return 1
  else:
    return 0

In [ ]:
def test_nn(input_dataset, first_layer_weights, target, size_of_data):
  res = 0
  for i in range(size_of_data):
    res += test(random.choice(input_dataset), first_layer_weights, target)
  return (res / size_of_data)

In [ ]:
print('Accuracy-score: ', test_nn(dataset, first_layer_weights, 1, 200))

Accuracy-score:  1.0


In [ ]:
first_layer_weights = np.ones((15, 1))
train_nn(dataset, first_layer_weights, 5, 8000)

In [ ]:
first_layer_weights

array([[ 0.7],
       [ 0.7],
       [ 0.7],
       [ 0.8],
       [ 1. ],
       [-0.2],
       [ 0.7],
       [ 0.9],
       [ 0.7],
       [-0.2],
       [ 1. ],
       [ 0.8],
       [ 0.7],
       [ 0.7],
       [ 0.7]])

In [ ]:
print('Accuracy-score: ', test_nn(dataset, first_layer_weights, 5, 2000))

Accuracy-score:  1.0


Попробуем создать зашумленный датасет и проверить как нейронная сеть справится с его обработкой

In [ ]:
noise_dataset = list()
for i in range(10000):
  noise_dataset.append(random.choice(numbers))
  for j in range(15):
    noise_dataset[i][0][j//3][j%3] += (random.randint(-2, 2) * 0.1)

In [ ]:
random.choice(noise_dataset)

([[2.600000000000001, -1.7999999999999998, -3.399999999999998],
  [-0.4000000000000018, -4.399999999999997, 5.899999999999996],
  [-1.9000000000000028, 3.399999999999998, -2.9000000000000017],
  [2.7000000000000006, -4.199999999999998, 3.600000000000002],
  [2.8999999999999915, 4.199999999999999, -9.399999999999993]],
 5)

In [ ]:
numbers = list()
numbers.append(([[1, 1, 1],
                 [1, 0, 1],
                 [1, 0, 1],
                 [1, 0, 1],
                 [1, 1, 1]], 0))

numbers.append(([[0, 0, 1],
                 [0, 0, 1],
                 [0, 0, 1],
                 [0, 0, 1],
                 [0, 0, 1]], 1))

numbers.append(([[1, 1, 1],
                 [0, 0, 1],
                 [1, 1, 1],
                 [1, 0, 0],
                 [1, 1, 1]], 2))

numbers.append(([[1, 1, 1],
                 [0, 0, 1],
                 [1, 1, 1],
                 [0, 0, 1],
                 [1, 1, 1]], 3))

numbers.append(([[1, 0, 1],
                 [1, 0, 1],
                 [1, 1, 1],
                 [0, 0, 1],
                 [0, 0, 1]], 4))

numbers.append(([[1, 1, 1],
                 [1, 0, 0],
                 [1, 1, 1],
                 [0, 0, 1],
                 [1, 1, 1]], 5))

numbers.append(([[1, 1, 1],
                 [1, 0, 0],
                 [1, 1, 1],
                 [1, 0, 1],
                 [1, 1, 1]], 6))

numbers.append(([[1, 1, 1],
                 [0, 0, 1],
                 [0, 0, 1],
                 [0, 0, 1],
                 [0, 0, 1]], 7))

numbers.append(([[1, 1, 1],
                 [1, 0, 1],
                 [1, 1, 1],
                 [1, 0, 1],
                 [1, 1, 1]], 8))

numbers.append(([[1, 1, 1],
                 [1, 0, 1],
                 [1, 1, 1],
                 [0, 0, 1],
                 [1, 1, 1]], 9))

In [ ]:
import copy
noise_dataset = list()
for i in range(10000):
  noise_dataset.append(copy.deepcopy(random.choice(numbers)))
  for j in range(15):
    noise_dataset[i][0][j//3][j%3] += (random.randint(-30, 30) * 0.01)

In [ ]:
random.choice(noise_dataset)

([[1.0, 1.03, 1.1400000000000001],
  [0.74, -0.29, -0.23],
  [1.02, 1.29, 0.98],
  [1.04, -0.03, 1.27],
  [0.95, 1.1400000000000001, 0.73]],
 6)

In [ ]:
first_layer_weights = np.ones((15, 1))
train_nn(noise_dataset, first_layer_weights, 4, 8000)

In [ ]:
train_nn(noise_dataset, first_layer_weights, 4, 8000)

In [ ]:
first_layer_weights

array([[ 1.654],
       [-2.968],
       [ 0.28 ],
       [ 2.205],
       [-0.464],
       [ 0.883],
       [ 1.848],
       [ 1.819],
       [ 0.745],
       [-0.805],
       [-0.281],
       [ 0.59 ],
       [-2.571],
       [-2.305],
       [ 0.695]])

In [ ]:
print('Accuracy-score: ', test_nn(noise_dataset, first_layer_weights, 4, 2000))

Accuracy-score:  1.0


Попробуем создать датасет с отсутствующей нормализацией некоторых значений

In [ ]:
dataset_without_normalize = list()
for i in range(10000):
  dataset_without_normalize.append(copy.deepcopy(random.choice(numbers)))
  for j in range(15):
    dataset_without_normalize[i][0][j//3][j%3] += (random.randint(-20, 20) * 0.01)
    if j in [1, 5, 9]:
      dataset_without_normalize[i][0][j//3][j%3] *= 255

In [ ]:
print(random.choice(dataset_without_normalize))

([[1.19, 219.29999999999998, 1.16], [1.06, -0.18, 214.2], [1.06, 1.06, 0.84], [260.1, 0.15, 0.97], [0.87, 1.03, 1.2]], 8)


In [ ]:
first_layer_weights = np.ones((15, 1))
train_nn(dataset_without_normalize, first_layer_weights, 9, 8000)

In [ ]:
train_nn(dataset_without_normalize, first_layer_weights, 9, 8000)

In [ ]:
print('Accuracy-score: ', test_nn(dataset_without_normalize, first_layer_weights, 9, 2000))

Accuracy-score:  0.669


Для сравнения проведем такой же эксперимент для датасета с нормализацией

In [ ]:
dataset_with_normalize = list()
for i in range(10000):
  dataset_with_normalize.append(copy.deepcopy(dataset_without_normalize[i]))
  for j in [1, 5, 9]:
    if dataset_with_normalize[i][0][j//3][j%3] != 0:
      dataset_with_normalize[i][0][j//3][j%3] /= 255

In [ ]:
print(random.choice(dataset_with_normalize))

([[0.9, 1.12, 1.05], [0.05, 0.2, 0.85], [-0.19, -0.14, 0.89], [0.06, -0.15, 0.92], [-0.12, 0.2, 1.11]], 7)


In [ ]:
first_layer_weights = np.ones((15, 1))
train_nn(dataset_with_normalize, first_layer_weights, 9, 8000)

In [ ]:
train_nn(dataset_with_normalize, first_layer_weights, 9, 8000)

In [ ]:
print('Accuracy-score: ', test_nn(dataset_with_normalize, first_layer_weights, 9, 2000))

Accuracy-score:  0.9965


##Практическая часть

In [ ]:
dataset = list()

dataset.append(([0, 0],0))
dataset.append(([0, 1],1))
dataset.append(([1, 0],1))
dataset.append(([1, 1],1))

In [ ]:
import copy
import random
noise_dataset = list()
for i in range(10000):
  noise_dataset.append(copy.deepcopy(random.choice(dataset)))
  for j in range(2):
    noise_dataset[i][0][j] += (random.randint(-45, 45) * 0.01)

In [ ]:
random.choice(noise_dataset)

([1.24, -0.18], 1)

**Задание (базовый уровень):**
Создать модель (без использования готовых решений) простейшего перцептрона, которая будет выполнять функцию логического "ИЛИ".

**Задание (повышенный уровень):**
Создать модель (без использования готовых решений) перцептрона, которая будет выполнять функцию исключающего "ИЛИ".

*Общее требование:*  Обучение и тестирование должно проходить на зашумленных данных (уровень шума +- 0.45). 